const adjustmentCodes = {
    "C1": "Pre-teach key topic vocabulary (meaning and spelling)",
    "C2": "Provide opportunity for student to preview new or unfamiliar work",
    "C3": "Highlight key content and vocabulary",
    "C4": "Modified instruction using a structured task-analysis approach",
    "C5": "Explicit step by step instruction of skills",
    "C6": "Present text and content in various formats: e.g., video, readings, lectures, audio",
    "C7": "Modified homework tasks",
    "C8": "Break larger tasks / content into smaller chunks",
    "C9": "Provide notes / summaries",
    "C10": "Use visual scaffolds / planners",
    "C11": "Curriculum compact and/or accelerate",
    "C12": "Cross Age Tutor",
    "C13": "Modified outcomes / reporting",
    "C14": "Other (Content)",
    "M1": "Provide clearly identified learning intention",
    "M2": "Provide paced instructions / step by step structure for a task",
    "M3": "Use repetition and slow task complexity",
    "M4": "Supporting understanding with visual cues and sub-headings",
    "M5": "Provide explicit instruction for each part of an activity",
    "M6": "Provide the student extra time to work through content / questions",
    "M7": "Write lesson structure on the board or desk in sequential order",
    "M8": "Specifically outline when the lesson transitions take place",
    "M9": "Check for understanding (ask student to paraphrase task expectations)",
    "M10": "Use pause time after questioning for language processing (EAL/D also)",
    "M11": "Use of peer tutoring and small group work during lessons",
    "M12": "Extra time to process and reflect information during the lesson",
    "M13": "Explicit teaching of summarisation and/or planning",
    "M14": "Provide extra practice opportunities to support understanding",
    "M15": "Make eye contact with student when giving instructions",
    "M16": "Reduce, repeat, re-phrase verbal information",
    "M17": "Active monitoring and supervision",
    "M18": "Other (Method) — e.g. subtitles/closed captioning",
    "P1": "Provide a range of worked examples in various formats",
    "P2": "Alternative learning experience / task to show understanding",
    "P3": "Use scaffolds to support writing and assessment tasks",
    "P4": "Allow student to type rather than handwrite",
    "P5": "Provide explicit and regular feedback on assessment tasks",
    "P6": "Provide special interest projects / choice of presentation",
    "P7": "Provide varied types of resources in preparing products",
    "P8": "Plan and consult with other specialists (Inclusive Learning)",
    "P9": "Utilise IT and Apps to facilitate communication and task completion",
    "P10": "Provide a checklist outlining task sections to be completed",
    "P11": "Provide a glossary of key terms and concepts",
    "P12": "Provide a list of check-in points to monitor assessment progress",
    "P13": "Other (Product)",
    "E1": "Specific seating plan / preferential seating",
    "E2": "Alternative classroom environments for learning",
    "E3": "Use of peer tutoring (or CAT)",
    "E4": "Allow student time out",
    "E5": "Provide regular structured classroom routine",
    "E6": "Specific adjustments to environment / practical task",
    "E7": "Arrange suitable grouping for group tasks",
    "E8": "Provide 1 to 1 support during lesson",
    "E9": "Specific classroom management procedures (safe/supportive environment)",
    "E10": "Teaching assistant to support learning in class",
    "E11": "Additional learning support through Inclusive Learning",
    "E12": "Use of specific behaviour strategies / rewards / praise",
    "E13": "Monitor understanding through questioning",
    "E14": "Other (Environment)",
    "D1": "Use of a reader",
    "D2": "Use of a writer",
    "D3": "Extra time",
    "D4": "Rest breaks",
    "D5": "Small group supervision",
    "D6": "Test print variation (enlarged / coloured paper / overlays)",
    "D7": "Adjusted / modified assessment task",
    "D8": "Other (Disability Provisions)",
    "HP-CX1": "Open-ended questions leading to deeper analysis",
    "HP-CX2": "Higher order skills: analysis, synthesis, creation",
    "HP-CX3": "Justification of thinking and reasoning through different means",
    "HP-CH1": "Pre-testing prior knowledge to inform teaching",
    "HP-CH2": "Justification of thinking",
    "HP-CH3": "Applying new skills and knowledge to different contexts",
    "HP-CH4": "Differentiated resources",
    "HP-CO1": "Planning open-ended tasks",
    "HP-CO2": "Designing tasks that tap into areas of interest",
    "HP-CO3": "Permitting diversity of modes of communication",
    "HP-PA1": "Compacting curriculum in areas of strength",
    "HP-PA2": "Increasing pace of instruction in areas of strength",
    "HP-LE1": "Encouraging experimentation and risk-taking",
    "HP-LE2": "Clearly communicating explicit criteria for success",
    "HP-LE3": "Check-ins to prompt support during activities",
    "HP-LE4": "Ensuring placement facilitates deep focus"
};
