// Search data - all strategies indexed with keywords
// Includes continuum fields, adjustment codes, and HP adjustment tags
const searchData = [
    {
        id: "kuds-1",
        title: "Clarify KUDs from Existing Materials",
        category: "KUDs",
        step: "Step 1: Establish KUDs",
        link: "step1-kuds.html",
        description: "Use AI to extract and clarify Know, Understand, and Do goals from your existing curriculum documents, programs, or syllabus outcomes.",
        keywords: ["KUDs","learning goals","learning intention","syllabus","curriculum","outcomes","clarify","existing","program"],
        whenToUse: "When you have existing curriculum materials and want to sharpen your learning goals into clear KUDs before differentiating.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Planning: defines the centre of the continuum",
        adjustmentCodes: ["M1"],
        hpAdjustments: ["HP-LE2"],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "kuds-2",
        title: "Test Your KUDs for Clarity",
        category: "KUDs",
        step: "Step 1: Establish KUDs",
        link: "step1-kuds.html",
        description: "Use AI to stress-test your KUDs for clarity, measurability, and alignment — ensuring they're specific enough to guide differentiation.",
        keywords: ["KUDs","test","clarity","check","review","measurable","specific","alignment","quality"],
        whenToUse: "After drafting your KUDs, to check they're clear and specific enough to differentiate effectively.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Planning: stress-tests the learning intention",
        adjustmentCodes: ["M1"],
        hpAdjustments: ["HP-LE2"],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "kuds-3",
        title: "Build KUDs from Scratch",
        category: "KUDs",
        step: "Step 1: Establish KUDs",
        link: "step1-kuds.html",
        description: "Use AI to help build KUDs from scratch when starting a new unit or topic, ensuring alignment with NSW syllabus outcomes.",
        keywords: ["KUDs","create","build","new","unit","planning","syllabus","from scratch","design"],
        whenToUse: "When planning a new unit and you need to establish clear learning goals from the ground up.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Planning: creates the learning intention from curriculum documents",
        adjustmentCodes: ["M1"],
        hpAdjustments: [],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "kuds-4",
        title: "Stress-Test Your Goals (Anticipatory Differentiation)",
        category: "KUDs",
        step: "Step 1: Establish KUDs",
        link: "step1-kuds.html",
        description: "Use AI to anticipate how different learners will engage with your KUDs — identifying potential barriers before you start planning differentiated instruction.",
        keywords: ["KUDs","stress-test","anticipate","barriers","readiness","differentiation","planning","proactive"],
        whenToUse: "After finalising KUDs, to predict where different learners might struggle and plan accordingly.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Planning: anticipates where different learners will need support",
        adjustmentCodes: ["M1","C2"],
        hpAdjustments: [],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "learners-1",
        title: "Create a Pre-Assessment",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to design a pre-assessment that reveals student readiness levels for a specific topic or skill, providing data to guide differentiation decisions.",
        keywords: ["pre-assessment","diagnostic","readiness","data","baseline","prior knowledge","assess","starting point"],
        whenToUse: "Before starting a new unit or topic, to find out what students already know and can do.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: reveals where each student sits relative to the core",
        adjustmentCodes: ["M9"],
        hpAdjustments: ["HP-CH1"],
        taskTypes: ["plan-unit", "plan-sequence", "create-assessment"]
    },
    {
        id: "learners-2",
        title: "Build a Deidentified Class Profile",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to help organise pre-assessment data into a class profile that groups students by readiness, interest, or learning profile — using deidentified data for privacy.",
        keywords: ["class profile","grouping","data","organise","readiness groups","deidentified","privacy","student data"],
        whenToUse: "After collecting pre-assessment data, to make sense of it and identify groupings for differentiation.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: organises student data to inform continuum decisions",
        adjustmentCodes: [],
        hpAdjustments: [],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "learners-3",
        title: "Discover Student Interests",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to design interest surveys or inventories that help you learn what students care about, providing data for interest-based differentiation.",
        keywords: ["interests","survey","motivation","engagement","student voice","choice","preferences","inventory"],
        whenToUse: "When you want to differentiate by interest but don't yet have data on what your students care about.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: gathers interest data for engagement-based differentiation",
        adjustmentCodes: [],
        hpAdjustments: ["HP-CO2"],
        taskTypes: ["diff-lesson", "plan-sequence", "plan-unit"]
    },
    {
        id: "learners-4",
        title: "Identify Misconceptions",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to predict common misconceptions students are likely to hold about a topic, helping you design pre-assessments and instruction that address them.",
        keywords: ["misconceptions","errors","confusion","prior knowledge","predict","common mistakes","understanding"],
        whenToUse: "When planning a new topic and you want to anticipate what students might misunderstand.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: predicts foundations-level barriers students may face",
        adjustmentCodes: ["C2"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence", "plan-unit"]
    },
    {
        id: "learners-5",
        title: "Differentiate for Learning Profiles",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to help identify and plan for different learning profiles in your class — including visual, auditory, kinesthetic preferences and neurodiversity considerations.",
        keywords: ["learning profile","learning style","visual","auditory","kinesthetic","neurodiversity","preferences","modality"],
        whenToUse: "When you want to understand and plan for the range of learning preferences in your class.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: maps learning preferences to inform content access",
        adjustmentCodes: ["C6","E6"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence", "plan-unit"]
    },
    {
        id: "learners-6",
        title: "Analyse Pre-Assessment Results",
        category: "Know Your Learners",
        step: "Step 2: Know Your Learners",
        link: "step2-learners.html",
        description: "Use AI to help interpret and act on pre-assessment data — turning raw results into actionable groupings and instructional recommendations.",
        keywords: ["analyse","results","data","interpret","grouping","recommendations","pre-assessment","action"],
        whenToUse: "After running a pre-assessment, to quickly make sense of the data and plan next steps.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Diagnostic: turns raw data into actionable groupings along the continuum",
        adjustmentCodes: ["M9","M17"],
        hpAdjustments: ["HP-CH1"],
        taskTypes: ["plan-unit", "plan-sequence"]
    },
    {
        id: "content-1",
        title: "Tiered Texts & Resource Materials",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Provide reading materials at different complexity and readability levels so students can engage with the same overarching theme or concept regardless of their current literacy skills.",
        keywords: ["text","reading","complexity","readability","tiered","levels","literacy","vocabulary","too hard","too easy","struggling readers","advanced readers","EAL","EALD"],
        whenToUse: "When the core content involves significant reading, and you have students at varied reading levels. This ensures all students can access the concepts without being blocked by text complexity.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "Creates three text versions at different complexity levels — foundations, core, and extension — all conveying the same concepts",
        adjustmentCodes: ["C3","C6","C9"],
        hpAdjustments: ["HP-CH4"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "content-2",
        title: "Multi-Modal Presentations",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Deliver information through multiple modes—auditory (recordings, discussions), visual (graphic organisers, diagrams, videos), and tactile/kinesthetic (hands-on models, movement).",
        keywords: ["visual","audio","video","kinesthetic","hands-on","multiple formats","learning styles","graphic organiser","diagram","recording","accessibility"],
        whenToUse: "When students have varied learning profiles or when content is complex and benefits from multiple representations. This is especially powerful for EALD students or students with learning differences.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core"],
        continuumPrimary: "core",
        continuumNote: "Delivering content through multiple modes — primarily a core-level access strategy, but serves as foundations support for students who need alternative entry points",
        adjustmentCodes: ["C6"],
        hpAdjustments: ["HP-CH4"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "content-3",
        title: "Curriculum Compacting",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "A three-stage process: (1) identify what students have already mastered through pre-assessment, (2) eliminate redundant practice for those students, (3) replace it with meaningful curriculum extensions or independent projects.",
        keywords: ["advanced","gifted","already know","skip","pre-assessment","extension","enrichment","mastery","redundant"],
        whenToUse: "When pre-assessment reveals that some students have already mastered portions of the content. This prevents boredom and allows advanced learners to move into deeper exploration.",
        continuumType: "fixed",
        continuumPosition: ["extension"],
        continuumPrimary: "extension",
        continuumNote: "Eliminates redundant practice for students who have mastered the core, replacing it with meaningful extension",
        adjustmentCodes: ["C11"],
        hpAdjustments: ["HP-PA1","HP-PA2"],
        taskTypes: ["plan-sequence", "plan-unit", "ideate-extension"]
    },
    {
        id: "content-4",
        title: "Digest of Key Ideas",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Create a one- or two-page \"capsule\" of essential questions, vocabulary, and concepts to support students who struggle with heavy print materials or organisation.",
        keywords: ["summary","overview","key points","study guide","reference","vocabulary","organization","struggling","overwhelmed"],
        whenToUse: "When students are overwhelmed by lengthy texts or complex materials. This gives them a roadmap and helps them focus on what matters most.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Distils essential content into a focused summary, reducing overwhelm for students who need a clearer path to the core learning intention",
        adjustmentCodes: ["C3","C9"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "ideate-support"]
    },
    {
        id: "content-5",
        title: "Highlighted Print Materials",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Highlight critical passages in a text so that struggling readers can focus energy on essential portions rather than becoming discouraged by an overwhelming amount of print.",
        keywords: ["highlight","emphasis","focus","essential","key points","attention","guide"],
        whenToUse: "When a lengthy text contains essential content, but not every paragraph is equally important. This helps students with reading challenges or executive functioning difficulties know where to focus.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Directs attention to critical passages, reducing cognitive load so students can focus energy on accessing the core concepts",
        adjustmentCodes: ["C3"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "ideate-support"]
    },
    {
        id: "content-6",
        title: "Support Systems (Buddies, Mentors, Technology)",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Use reading buddies, adult mentors, or audio/video recordings to make complex content accessible to all students.",
        keywords: ["buddies","mentors","technology","support","audio","recording","reading buddy","peer support","accessibility","EALD"],
        whenToUse: "When content is challenging but essential, and students need human or technological support to access it. This is particularly effective for EALD students or students with reading difficulties.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Provides human or technological support to help students access content that would otherwise be beyond their independent reach",
        adjustmentCodes: ["C12","E3","E8"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "setup-systems", "ideate-support"]
    },
    {
        id: "content-7",
        title: "Visual Supports: Glossaries, Mind Maps, Flashcards",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Provide visual tools that help students organise, remember, and connect content. These can be pre-made or co-created with students.",
        keywords: ["visual","glossary","mind map","flashcard","organise","connect","memory","vocabulary","relationships"],
        whenToUse: "When content is vocabulary-heavy, conceptually dense, or requires students to see relationships between ideas. Visual supports are especially helpful for visual learners and students who struggle with working memory.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core"],
        continuumPrimary: "foundations",
        continuumNote: "Visual tools for organising and connecting content — primarily foundations scaffolding, but mind maps are also used as core-level thinking tools",
        adjustmentCodes: ["C1","C3","C10","P11"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "ideate-support", "diff-lesson"]
    },
    {
        id: "content-8",
        title: "Neurodiversity-Responsive Content Design",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Design content that is accessible for neurodivergent learners by reducing cognitive load, providing multimodal formats, using concrete language, and offering strength-based supports. This approach benefits all students while specifically supporting those with ADHD, autism spectrum disorder, dyslexia, and executive functioning challenges.",
        keywords: ["neurodiversity","ADHD","autism","dyslexia","cognitive load","concrete language","accessibility","working memory","executive function"],
        whenToUse: "When you have students with diagnosed learning differences, when content involves complex language or multi-step processes, or when you want to make content universally accessible from the start.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Redesigns content to reduce barriers for neurodivergent learners — building the bridge to core content",
        adjustmentCodes: ["C4","C6","C8","M4"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "plan-sequence", "plan-unit", "ideate-support"]
    },
    {
        id: "process-1",
        title: "Tiered Activities",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Design multiple versions of a task that focus on the same essential understanding but vary in complexity, abstraction, and required support. All students work toward the same learning goals, but the pathway differs based on readiness.",
        keywords: ["tiered","levels","challenge","complexity","varied difficulty","ZPD","readiness","scaffolding"],
        whenToUse: "When students have varied readiness levels for a particular skill or concept. Tiering ensures everyone is appropriately challenged—working in their Zone of Proximal Development, not too easy, not impossibly hard.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "The archetypal full-span strategy — creates multiple task versions at different complexity levels, all targeting the same learning intention",
        adjustmentCodes: ["C4","M3"],
        hpAdjustments: ["HP-CX2","HP-CH4"],
        taskTypes: ["diff-lesson", "plan-sequence", "ideate-support", "ideate-extension"]
    },
    {
        id: "process-2",
        title: "Flexible Grouping",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Move students between various group configurations based on the task at hand. Sometimes group by readiness (homogeneous), sometimes by interest (mixed), sometimes randomly. The key word is flexible—groups change frequently to prevent tracking.",
        keywords: ["grouping","groups","flexible groups","homogeneous","heterogeneous","partners","teams","collaboration","peer learning"],
        whenToUse: "Constantly. Flexible grouping is considered the \"heart\" of differentiation. It allows you to target instruction to specific needs while ensuring students don't get stuck in permanent ability groups.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "The grouping structure itself operates at core level, but strategic grouping enables foundations support and extension challenge",
        adjustmentCodes: ["E7","M11"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence", "plan-unit", "setup-systems"]
    },
    {
        id: "process-3",
        title: "Learning Centres/Stations",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Designated classroom areas where students rotate through different activities to explore topics or practice skills at their own pace. Centres allow for simultaneous differentiation—different students working on different things at the same time.",
        keywords: ["centers","stations","rotation","small group","independent work","variety","engagement"],
        whenToUse: "When you want students to practice skills or explore concepts independently or in small groups. Works well for skill reinforcement, application activities, or exploratory learning.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "Stations can be designed at different levels — some scaffold, some operate at core, some extend — running simultaneously",
        adjustmentCodes: ["C6","M6","M14"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence", "setup-systems"]
    },
    {
        id: "process-4",
        title: "Cubing",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "A strategy where students analyse a topic from six different perspectives (like the six sides of a cube): describe it, compare it, associate it, analyse it, apply it, argue for/against it. You can create different cubes for different readiness levels.",
        keywords: ["cubing","cube","perspectives","analysis","multiple angles","six sides","thinking","Bloom's"],
        whenToUse: "When you want students to explore a concept from multiple angles. Cubing works well for review, application, or deeper exploration of content students have already encountered.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "Different cubes can be created at foundations, core, and extension levels — the six-perspective structure applies at any point on the continuum",
        adjustmentCodes: [],
        hpAdjustments: ["HP-CX1","HP-CX2"],
        taskTypes: ["diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "process-5",
        title: "Jigsaw",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "A cooperative learning strategy where students become \"experts\" in one aspect of a topic, then teach that aspect to their peers. Students start in \"expert groups,\" then move to \"home groups\" to share their expertise.",
        keywords: ["jigsaw","cooperative","expert groups","home groups","peer teaching","collaboration","interdependence"],
        whenToUse: "When a topic has multiple distinct parts that can be learned somewhat independently. Jigsaw promotes interdependence—everyone needs everyone else—and gives students practice teaching.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Primarily a core collaborative strategy where all students contribute, but topic assignment can be differentiated by readiness",
        adjustmentCodes: ["M11","E7"],
        hpAdjustments: [],
        taskTypes: ["plan-sequence", "plan-unit", "ideate-extension"]
    },
    {
        id: "process-6",
        title: "Learning Contracts",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Formal agreements between teacher and student where the teacher grants freedom in how class time is used in exchange for the student completing individualized skill or content components. Contracts outline what must be done, by when, and to what standard.",
        keywords: ["contract","independence","self-directed","goals","agreement","accountability","personalised"],
        whenToUse: "When students are ready for more independence and self-direction. Works well for extensions, independent projects, or when students need to work on specific skills at their own pace.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "extension",
        continuumNote: "Formal agreements granting independence — most commonly used for extension students who can self-direct",
        adjustmentCodes: ["M6","P6"],
        hpAdjustments: ["HP-CO1","HP-CO2"],
        taskTypes: ["plan-sequence", "plan-unit", "ideate-extension"]
    },
    {
        id: "process-7",
        title: "Interactive Journals",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Journals where students respond to varied writing prompts based on their readiness level. Students reflect on and \"own\" ideas from their reading and learning. Teacher provides feedback, creating a dialogue.",
        keywords: ["journal","writing","reflection","dialogue","processing","personal response","readiness"],
        whenToUse: "When you want students to process and personalise content through writing. Works well for ongoing reflection, connecting new learning to prior knowledge, or exploring concepts more deeply.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: "core",
        continuumNote: "Journal prompts can be pitched at any level — structured at foundations, reflective at core, analytical at extension",
        adjustmentCodes: ["M13","M14"],
        hpAdjustments: ["HP-CX3"],
        taskTypes: ["diff-lesson", "plan-sequence", "create-assessment"]
    },
    {
        id: "process-8",
        title: "Anchor Activities",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Self-directed tasks that students move to automatically upon completing assigned work. Anchor activities manage \"ragged time\" in a differentiated classroom where students finish at different rates.",
        keywords: ["anchor","early finishers","waiting","extension","enrichment","independent work"],
        whenToUse: "Always. In any differentiated classroom, students will finish tasks at different times. Anchor activities prevent the \"I'm done, what do I do now?\" problem and keep learning happening for everyone.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "extension",
        continuumNote: "Self-directed tasks for students who finish early — typically pitched at core consolidation or extension",
        adjustmentCodes: ["M6","M14"],
        hpAdjustments: ["HP-CO1"],
        taskTypes: ["diff-lesson", "plan-sequence"]
    },
    {
        id: "product-1",
        title: "Choice Boards & Menus",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Grids or menus of activity options that allow students to select how they will demonstrate learning. Students choose from multiple product options, all of which address the same learning goals but offer different ways to show mastery.",
        keywords: ["choice","menu","options","selection","variety","student choice","interest","flexibility"],
        whenToUse: "When you want to give students agency in how they demonstrate learning. Choice boards work well for culminating projects, application tasks, or ongoing skill practice. They increase engagement by honoring student preferences.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "extension",
        continuumNote: "Gives students agency in demonstration format — primarily core/extension, but tiered versions can include scaffolded options",
        adjustmentCodes: ["P2","P6","P7"],
        hpAdjustments: ["HP-CO2","HP-CO3"],
        taskTypes: ["create-assessment", "plan-sequence", "plan-unit"]
    },
    {
        id: "product-2",
        title: "RAFT (Role, Audience, Format, Topic)",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "A technique where students demonstrate learning by taking on a specific Role, writing for a targeted Audience, in a chosen Format, about a specified Topic. RAFT makes learning feel more authentic and engaging.",
        keywords: ["RAFT","role","audience","format","perspective","writing","creativity","authentic"],
        whenToUse: "When you want students to apply content knowledge in creative, authentic ways. RAFT works especially well for content that can be viewed from multiple perspectives or communicated to different audiences.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "RAFT assignments can be tiered by readiness — simpler roles for foundations, complex perspectives for extension",
        adjustmentCodes: ["P2","P6"],
        hpAdjustments: ["HP-CO2"],
        taskTypes: ["create-assessment", "diff-lesson"]
    },
    {
        id: "product-3",
        title: "Negotiated Criteria",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Collaborate with students to determine the core requirements for a product while allowing them to add personal quality goals. Students have voice in what \"excellent work\" looks like while ensuring essential elements are present.",
        keywords: ["negotiated","criteria","co-create","student voice","success criteria","quality","ownership","rubric"],
        whenToUse: "When you want to build student ownership and agency while maintaining rigor. Works well for projects where students have choice in format but you need to ensure certain learning goals are demonstrated.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Co-creating success criteria operates at core level, but personal quality goals extend into extension territory",
        adjustmentCodes: ["P5","P10"],
        hpAdjustments: ["HP-LE2"],
        taskTypes: ["create-assessment", "ideate-extension"]
    },
    {
        id: "product-4",
        title: "Tiered Assessments",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Provide multiple versions of a summative task that assess the same standards but vary in complexity, scaffolding, or mode of expression. All students demonstrate the same learning goals, but the pathway to demonstrating them differs.",
        keywords: ["tiered","assessment","levels","complexity","scaffolding","readiness","summative","varied difficulty"],
        whenToUse: "When students have significantly varied readiness levels and you want to assess their learning accurately without ceiling or floor effects. Tiered assessments ensure you see what students actually know, not what they can't access due to task design.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "Creates multiple assessment versions at different complexity levels — the product equivalent of Tiered Activities",
        adjustmentCodes: ["C4","P2","P3","D7"],
        hpAdjustments: ["HP-CH4"],
        taskTypes: ["create-assessment", "plan-sequence"]
    },
    {
        id: "product-5",
        title: "Expanding the Product Repertoire with AI",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "AI tools make it possible to support students in creating products that were previously too complex or time-consuming to scaffold. Consider these possibilities:",
        keywords: ["AI","technology","digital","podcast","animation","infographic","non-traditional","creative","new formats"],
        whenToUse: "",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "AI enables non-traditional products — these typically operate at core or extension level, with AI providing the technical scaffolding",
        adjustmentCodes: ["P7","P9"],
        hpAdjustments: ["HP-CO3"],
        taskTypes: ["create-assessment", "plan-unit"]
    },
    {
        id: "product-6",
        title: "Performance & Presentation Products",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Some students demonstrate their learning best through performance—presenting, demonstrating, teaching, or performing for an audience.",
        keywords: ["performance","presentation","oral","demonstrate","audience","speaking","public speaking"],
        whenToUse: "When learning involves demonstrable skills, when public speaking is a goal, or when students excel at oral communication over written.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Performance tasks can be pitched at any level — a simple demonstration at core, a persuasive presentation at extension",
        adjustmentCodes: ["P2"],
        hpAdjustments: ["HP-CO3"],
        taskTypes: ["create-assessment"]
    },
    {
        id: "product-7",
        title: "Creative & Artistic Products",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Creative products allow students to demonstrate understanding through art, design, storytelling, or creative expression.",
        keywords: ["creative","art","artistic","design","storytelling","expression","visual","craft"],
        whenToUse: "When content has emotional, thematic, or interpretive dimensions; when students need alternative ways to show understanding.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Creative expression as demonstration — primarily core level, with extension when students interpret or create for specific audiences",
        adjustmentCodes: ["P2","P7"],
        hpAdjustments: ["HP-CO3"],
        taskTypes: ["create-assessment", "ideate-support"]
    },
    {
        id: "product-8",
        title: "Collaborative Group Products",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Some learning is best demonstrated through collaboration—products that require students to work together and create something no individual could create alone.",
        keywords: ["group work","collaboration","teamwork","roles","cooperative learning"],
        whenToUse: "When learning goals include collaboration skills, when tasks benefit from multiple perspectives, or when product scope requires distributed effort.",
        continuumType: "flexible",
        continuumPosition: ["core"],
        continuumPrimary: "core",
        continuumNote: "Group products primarily operate at core level — the collaboration IS the learning",
        adjustmentCodes: ["E7","M11"],
        hpAdjustments: [],
        taskTypes: ["create-assessment", "plan-sequence"]
    },
    {
        id: "environment-1",
        title: "Flexible Seating",
        category: "Environment",
        step: "Step 3: Environment",
        link: "step3-environment.html",
        description: "Offer various seating options—traditional desks, floor seating, standing desks, balance balls, cushions—to meet students' physical needs for movement, comfort, and different working positions.",
        keywords: ["seating","furniture","workspace","flexible","choice","comfort","physical space"],
        whenToUse: "Ongoing. Some students focus better when moving, some need quiet stability, some benefit from ergonomic variety. Flexible seating honours these different physical needs.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Enabling: creates physical conditions that support all positions on the continuum",
        adjustmentCodes: ["E1","E2"],
        hpAdjustments: ["HP-LE4"],
        taskTypes: ["setup-systems"]
    },
    {
        id: "environment-2",
        title: "Learning Zones",
        category: "Environment",
        step: "Step 3: Environment",
        link: "step3-environment.html",
        description: "Create designated areas for different types of work: quiet individual work, collaboration spaces, technology zones, hands-on activity areas. Students move to the zone that matches their current task and needs.",
        keywords: ["zones","areas","spaces","classroom layout","quiet zone","collaboration space","technology zone","flexible space"],
        whenToUse: "When you want to support students in making choices about where and how they work best. Learning zones help students understand that different tasks require different environments.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Enabling: designates spaces for different types of work",
        adjustmentCodes: ["E2","E6"],
        hpAdjustments: ["HP-LE4"],
        taskTypes: ["setup-systems", "diff-lesson"]
    },
    {
        id: "environment-3",
        title: "Growth Mindset Culture",
        category: "Environment",
        step: "Step 3: Environment",
        link: "step3-environment.html",
        description: "Foster a classroom atmosphere that celebrates diversity, values effort and growth over \"innate ability,\" and views mistakes as learning opportunities. The psychological environment is as important as the physical one.",
        keywords: ["growth mindset","culture","effort","mistakes","learning","psychological safety","belonging","attitudes"],
        whenToUse: "Always. Growth mindset isn't a one-time lesson—it's woven into how you respond to student work, how you frame challenges, and how you celebrate progress.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Enabling: builds the psychological safety that makes movement along the continuum possible",
        adjustmentCodes: ["E9","E12"],
        hpAdjustments: ["HP-LE1"],
        taskTypes: ["setup-systems"]
    },
    {
        id: "environment-4",
        title: "Sensory & Emotional Environment",
        category: "Environment",
        step: "Step 3: Environment",
        link: "step3-environment.html",
        description: "Consider sensory needs (lighting, noise level, visual clutter) and emotional safety (predictability, belonging, psychological safety to take risks). These factors significantly impact student ability to learn.",
        keywords: ["sensory","environment","noise","lighting","calm","stimulation","emotional safety","atmosphere"],
        whenToUse: "As part of your overall classroom design. Some students are highly sensitive to sensory input; others need sensory stimulation. Creating options supports diverse needs.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Enabling: addresses sensory and emotional needs that prevent access to any point on the continuum",
        adjustmentCodes: ["E4","E6","E9"],
        hpAdjustments: ["HP-LE4"],
        taskTypes: ["setup-systems", "diff-lesson"]
    },
    {
        id: "align-1",
        title: "Readiness-Based Differentiation",
        category: "Alignment",
        step: "Step 4: Align Strategy",
        link: "step4-align.html",
        description: "Match differentiation strategies to student readiness levels — adjusting challenge so all students work in their Zone of Proximal Development. Includes prompts for creating readiness-based groups and entry points.",
        keywords: ["readiness","ZPD","zone of proximal development","challenge","level","ability","grouping","tiered","entry points","pre-assessment"],
        whenToUse: "When you have pre-assessment data showing students at different readiness levels and need to match your differentiation approach accordingly.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Meta-framework: the rationale for placing students at different continuum positions",
        adjustmentCodes: ["C4","M3"],
        hpAdjustments: [],
        taskTypes: []
    },
    {
        id: "align-2",
        title: "Interest-Based Differentiation",
        category: "Alignment",
        step: "Step 4: Align Strategy",
        link: "step4-align.html",
        description: "Connect content to what students care about by designing interest-based exploration options, choice boards, and sidebar studies that maintain rigorous KUDs while increasing engagement.",
        keywords: ["interest","motivation","engagement","choice","relevance","connect","passion","sidebar study","student voice"],
        whenToUse: "When you want to increase engagement by connecting required content to student interests, or when designing choice-based activities.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Meta-framework: connects content to student interests — operates across all continuum positions",
        adjustmentCodes: ["P6"],
        hpAdjustments: ["HP-CO2"],
        taskTypes: []
    },
    {
        id: "align-3",
        title: "Profile-Based Differentiation",
        category: "Alignment",
        step: "Step 4: Align Strategy",
        link: "step4-align.html",
        description: "Adjust how students engage with content based on learning style, working preference, or cultural and linguistic background. Includes prompts for visual/auditory/kinesthetic versions and culturally responsive design.",
        keywords: ["learning profile","learning style","visual","auditory","kinesthetic","working preference","cultural","linguistic","EALD","modality"],
        whenToUse: "When you want to honour different learning preferences or cultural backgrounds in how students access and engage with content.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Meta-framework: adjusts modality and cultural responsiveness",
        adjustmentCodes: ["C6","E6"],
        hpAdjustments: [],
        taskTypes: []
    },
    {
        id: "align-4",
        title: "Combining Multiple Differentiation Factors",
        category: "Alignment",
        step: "Step 4: Align Strategy",
        link: "step4-align.html",
        description: "Design differentiated instruction that addresses readiness AND interest AND learning profile simultaneously — the most sophisticated form of responsive teaching.",
        keywords: ["multiple factors","combine","readiness","interest","profile","complex","sophisticated","responsive","comprehensive"],
        whenToUse: "When you need to differentiate across multiple dimensions at once — considering readiness, interest, and learning profile together.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Meta-framework: combines readiness + interest + profile simultaneously",
        adjustmentCodes: ["C4","C6","P6"],
        hpAdjustments: [],
        taskTypes: []
    },
    {
        id: "equalizer-1",
        title: "Foundational ↔ Transformational",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the foundational-to-transformational continuum. Foundational tasks focus on clear, straightforward application; transformational tasks require students to use ideas in new and unfamiliar ways.",
        keywords: ["foundational","transformational","challenge","complexity","application","transfer","equalizer","continuum"],
        whenToUse: "When adjusting the level of cognitive demand — from practising ideas in straightforward ways to applying them in new, unfamiliar contexts.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts whether students apply ideas in straightforward ways (foundations) or in new, unfamiliar ways (extension)",
        adjustmentCodes: ["C4","M3"],
        hpAdjustments: ["HP-CX2","HP-CH3"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-2",
        title: "Concrete ↔ Abstract",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the concrete-to-abstract continuum. Concrete tasks use tangible examples and specific details; abstract tasks require students to work with underlying principles and generalisations.",
        keywords: ["concrete","abstract","tangible","examples","principles","generalisation","equalizer","continuum"],
        whenToUse: "When some students need concrete, tangible examples while others are ready to work with abstract concepts and underlying principles.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts whether students work with tangible examples (foundations) or underlying principles (extension)",
        adjustmentCodes: ["C4","M4"],
        hpAdjustments: ["HP-CX2"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-3",
        title: "Simple ↔ Complex",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the simple-to-complex continuum. Simple tasks involve fewer steps and variables; complex tasks involve multiple steps, variables, and perspectives.",
        keywords: ["simple","complex","steps","variables","multi-step","perspectives","equalizer","continuum"],
        whenToUse: "When you need to adjust the number of moving parts in a task — fewer steps and variables for some, more interconnected elements for others.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts the number of variables, steps, and interconnections — fewer for foundations, more for extension",
        adjustmentCodes: ["C4","C8"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-4",
        title: "Single Facet ↔ Multiple Facets",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the single-to-multiple facets continuum. Single-facet tasks focus on one perspective or discipline; multiple-facet tasks require integrating across perspectives.",
        keywords: ["single facet","multiple facets","perspectives","interdisciplinary","integration","viewpoints","equalizer","continuum"],
        whenToUse: "When adjusting how many perspectives or disciplines students need to consider — from focused single-lens tasks to integrated multi-perspective work.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts whether students focus on one perspective or integrate across multiple perspectives",
        adjustmentCodes: [],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-5",
        title: "Small Leap ↔ Great Leap",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the small-to-great leap continuum. Small leaps apply learning in similar contexts; great leaps require significant transfer to new or unfamiliar situations.",
        keywords: ["small leap","great leap","transfer","application","familiar","unfamiliar","new context","equalizer","continuum"],
        whenToUse: "When adjusting how far students need to transfer their learning — from applying in familiar contexts to making connections across very different situations.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts transfer distance — familiar contexts (foundations) vs very different situations (extension)",
        adjustmentCodes: [],
        hpAdjustments: ["HP-CH3"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-6",
        title: "Structured ↔ Open-Ended",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the structured-to-open-ended continuum. Structured tasks provide clear steps and parameters; open-ended tasks require students to make decisions about approach and direction.",
        keywords: ["structured","open-ended","freedom","choice","autonomy","direction","parameters","equalizer","continuum"],
        whenToUse: "When adjusting how much structure or freedom students have — from clear step-by-step guidance to open-ended tasks requiring independent decision-making.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts structure — clear step-by-step guidance (foundations) vs open-ended decision-making (extension)",
        adjustmentCodes: ["C4","C5","M2"],
        hpAdjustments: ["HP-CX1","HP-CO1"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-7",
        title: "Dependent ↔ Independent",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust tasks along the dependent-to-independent continuum. Dependent tasks provide more teacher or peer support; independent tasks require students to work autonomously.",
        keywords: ["dependent","independent","autonomy","support","self-directed","teacher support","peer support","equalizer","continuum"],
        whenToUse: "When adjusting how much support students receive — from guided, scaffolded work to fully independent practice.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts the level of support — guided work (foundations) vs fully autonomous work (extension)",
        adjustmentCodes: ["E8","M6"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "equalizer-8",
        title: "Slow ↔ Fast",
        category: "Equalizer",
        step: "Step 5: The Equalizer",
        link: "step5-equalizer.html",
        description: "Adjust the pace of learning along the slow-to-fast continuum. Some students need more time to process and practice; others are ready to move quickly through material.",
        keywords: ["slow","fast","pace","speed","time","processing","quick","extended time","equalizer","continuum"],
        whenToUse: "When adjusting the pace at which students move through material — allowing more processing time for some while accelerating for others.",
        continuumType: "equaliser",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Adjusts pacing — more processing time (foundations) vs accelerated pace (extension)",
        adjustmentCodes: ["M6","M12","D3"],
        hpAdjustments: ["HP-PA2"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support", "ideate-extension"]
    },
    {
        id: "scaffolding-1",
        title: "Graphic Organizers",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Visual frameworks that help students organise thinking, see relationships between ideas, or structure their work. Particularly helpful for students who struggle with working memory or organisation.",
        keywords: ["graphic organiser","visual","framework","organiser","structure","map","diagram","chart","Venn","thinking"],
        whenToUse: "When students understand concepts but struggle to organise or connect ideas. When tasks require holding multiple pieces of information in mind simultaneously.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core"],
        continuumPrimary: "foundations",
        continuumNote: "Provides visual structure for organising thinking — primarily a foundations scaffold, but also used at core level as a thinking tool",
        adjustmentCodes: ["C10","M4","M13"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "scaffolding-2",
        title: "Sentence Starters & Thinking Stems",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Phrases that help students begin their thinking, writing, or discussion. Particularly helpful for students who know what they want to say but struggle to start, or who need models for academic language.",
        keywords: ["sentence starters","sentence frames","language scaffolds","writing support","academic language","thinking stems","EALD"],
        whenToUse: "For writing tasks, class discussions, or any time students need to articulate thinking in academic language. Especially helpful for EALD students.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Provides language scaffolds that help students begin articulating thinking",
        adjustmentCodes: ["C1","P3","M16"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "scaffolding-3",
        title: "Chunking & Step-by-Step Instructions",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Breaking complex tasks into smaller, manageable steps. Particularly helpful for students who feel overwhelmed by large tasks or have executive functioning challenges.",
        keywords: ["chunking","breaking down","steps","manageable","small pieces","simplify","sequence","executive function"],
        whenToUse: "When students understand the content but struggle with multi-step processes or feel paralyzed by complex assignments.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Breaks complex tasks into manageable steps, reducing cognitive overload",
        adjustmentCodes: ["C5","C8","M2","M5"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "ideate-support"]
    },
    {
        id: "scaffolding-4",
        title: "Models & Exemplars",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Showing students what quality work looks like. Models provide concrete examples of expectations rather than abstract descriptions.",
        keywords: ["example","model","sample","exemplar","demonstration","what good looks like","quality","expectations"],
        whenToUse: "When introducing new formats, genres, or quality standards. When students ask \"What do you mean?\" about expectations.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core"],
        continuumPrimary: "foundations",
        continuumNote: "Shows students what quality work looks like — primarily foundations, but exemplars also serve core-level learners",
        adjustmentCodes: ["P1","M4"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "scaffolding-5",
        title: "Thinking Partners & Collaboration",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Pairing students strategically so they can support each other's thinking. The right partnership can scaffold learning through dialogue and shared problem-solving.",
        keywords: ["partners","pairing","collaboration","dialogue","peer support","thinking","discussion","strategic pairing"],
        whenToUse: "When students would benefit from talking through ideas, when multiple perspectives would deepen understanding, or when peer explanation could clarify confusion.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: "core",
        continuumNote: "Strategic pairing supports learning at any level depending on how partners are matched",
        adjustmentCodes: ["E3","E7","M11"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "ideate-support"]
    },
    {
        id: "scaffolding-6",
        title: "Worked Examples & Think-Alouds",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Demonstrating the thinking process, not just the final answer. Show students how an expert approaches the task, including false starts and self-correction.",
        keywords: ["worked example","think aloud","demonstration","explicit instruction","showing thinking","teacher demonstration","modelling"],
        whenToUse: "When introducing new skills or problem types. When students know what to do but not how to think through it.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Demonstrates expert thinking processes, making invisible reasoning visible",
        adjustmentCodes: ["C5","M5","P1"],
        hpAdjustments: [],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "scaffolding-7",
        title: "Academic Language & Vocabulary Scaffolds",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Provide explicit support for academic vocabulary through student-friendly definitions, organised word walls, visual supports, and opportunities for practice. These scaffolds help all students—especially EALD learners—access content-heavy material and develop academic language proficiency.",
        keywords: ["vocabulary","academic language","word walls","glossary","language","terminology","EAL","EALD"],
        whenToUse: "When content involves Tier 2 (high-utility academic words) or Tier 3 (domain-specific terminology), when students need to understand and use specific vocabulary, or when supporting EALD students.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Provides explicit vocabulary support so academic language does not become a barrier",
        adjustmentCodes: ["C1","C3","P11"],
        hpAdjustments: [],
        taskTypes: ["plan-sequence", "plan-unit"]
    },
    {
        id: "assessment-1",
        title: "Exit Cards / Tickets",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Brief written responses students complete at the end of a lesson. These provide you with snapshot data about what students understood (or didn't) that you can use to plan tomorrow's instruction.",
        keywords: ["exit ticket","exit card","exit slip","formative assessment","check for understanding","quick assessment"],
        whenToUse: "End of most lessons, particularly after introducing new concepts or completing key activities.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Assessment: gathers data on where students sit relative to the core learning intention",
        adjustmentCodes: ["M9","M17"],
        hpAdjustments: ["HP-CH1","HP-LE3"],
        taskTypes: ["diff-lesson", "create-assessment"]
    },
    {
        id: "assessment-2",
        title: "QuickWrites",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Brief, timed writing activities (2-3 minutes) that ask students to synthesise learning or respond to a prompt. These reveal student thinking and provide formative data.",
        keywords: ["quick write","writing","timed","synthesis","formative","brief response","processing"],
        whenToUse: "Mid-lesson to check understanding before moving on, or to help students process what they've just learned.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Primarily a core-level processing strategy, but prompts can push toward extension",
        adjustmentCodes: ["M9","M13"],
        hpAdjustments: ["HP-CX3"],
        taskTypes: ["diff-lesson", "create-assessment"]
    },
    {
        id: "assessment-3",
        title: "Think-Pair-Share & Structured Discussion",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Give students a moment to think individually, then discuss with a partner, then share with the class. While students talk, you circulate and listen—gathering formative data about understanding.",
        keywords: ["think-pair-share","discussion","partner talk","peer learning","formative","sharing","processing"],
        whenToUse: "Throughout lessons to check understanding, activate prior knowledge, or process new information.",
        continuumType: "flexible",
        continuumPosition: ["core"],
        continuumPrimary: "core",
        continuumNote: "A core-level processing strategy that gives all students a structured way to engage",
        adjustmentCodes: ["M10","M11","M12"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson"]
    },
    {
        id: "assessment-4",
        title: "Dry Erase Boards / Immediate Response",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Students show their answers simultaneously on whiteboards (or digital equivalents). You can immediately see who gets it and who doesn't.",
        keywords: ["whiteboard","response cards","individual responses","whole class","quick check","immediate","visible"],
        whenToUse: "For quick checks during instruction, practicing skills, or gauging readiness before moving on.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Assessment: quick check tool for gauging understanding",
        adjustmentCodes: ["M9","M17"],
        hpAdjustments: ["HP-LE3"],
        taskTypes: ["plan-sequence", "plan-unit", "create-assessment"]
    },
    {
        id: "assessment-5",
        title: "Varying Questions by Readiness",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "During class discussion, target different questions to different students based on their readiness. This ensures all students are held accountable and appropriately challenged.",
        keywords: ["questioning","readiness","targeted questions","discussion","differentiated","Bloom's","tiered questions","challenge"],
        whenToUse: "During whole-class discussions and questioning.",
        continuumType: "full-span",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: null,
        continuumNote: "Targets different questions to different students — foundations, core, and extension simultaneously",
        adjustmentCodes: ["M3","M9","M10"],
        hpAdjustments: ["HP-CX1"],
        taskTypes: ["diff-lesson"]
    },
    {
        id: "assessment-6",
        title: "S-O-S Summary (Statement-Opinion-Support)",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Students write a brief response: State an opinion on a statement (agree/disagree), then support it with evidence. Provides practice for critical thinking without requiring a full essay.",
        keywords: ["SOS","statement","opinion","support","evidence","argumentation","critical thinking","quick response"],
        whenToUse: "When you want students to practice argumentation and evidence-based thinking in a low-stakes, quick format.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "extension",
        continuumNote: "A thinking routine that practises argumentation — core as base, extension for complex statements",
        adjustmentCodes: ["M13"],
        hpAdjustments: ["HP-CX1","HP-CX3","HP-CH2"],
        taskTypes: ["diff-lesson"]
    },
    {
        id: "assessment-7",
        title: "Observation Protocols with Rubrics",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Use a simple observation rubric to systematically note student progress during activities. A 4-point scale with clear descriptors helps you quickly identify understanding levels without disrupting the flow of teaching.",
        keywords: ["observation","rubric","monitoring","anecdotal","notes","watching","informal assessment","4-point scale"],
        whenToUse: "During independent work, group activities, or discussions when you want to systematically track who understands and who needs support.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Assessment: systematic teacher observation tool",
        adjustmentCodes: ["M17","E13"],
        hpAdjustments: ["HP-LE3"],
        taskTypes: ["diff-lesson", "create-assessment"]
    },
    {
        id: "assessment-8",
        title: "Quick Feedback Based on Common Responses",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Anticipate typical student responses and prepare targeted feedback ahead of time. This allows you to give specific, actionable feedback quickly when you're circulating or reviewing student work.",
        keywords: ["feedback","anticipated responses","common errors","targeted","prepared","specific","actionable","responsive"],
        whenToUse: "When planning a task or question where you can predict common correct, partially correct, and incorrect responses.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Assessment: prepares differentiated feedback — teacher planning tool",
        adjustmentCodes: ["P5"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson"]
    },
    {
        id: "assessment-9",
        title: "Peer Assessment Checklists",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Scaffold peer feedback with simple \"Got it / Need help\" checklists focused on success criteria. This builds students' assessment literacy while providing you with multiple data points on student work.",
        keywords: ["peer assessment","checklist","feedback","peer review","success criteria","assessment literacy","self-assessment"],
        whenToUse: "When students can meaningfully assess each other's work against clear criteria, particularly for drafts or work-in-progress.",
        continuumType: "flexible",
        continuumPosition: ["core","extension"],
        continuumPrimary: "core",
        continuumNote: "Primarily core-level, with extension potential for evaluating quality",
        adjustmentCodes: ["M11","P5","P10"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence"]
    },
    {
        id: "assessment-10",
        title: "Digital Exit Tickets (Google Forms)",
        category: "Assessment",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Use Google Forms for quick digital exit tickets that automatically compile student responses into a spreadsheet, making data analysis faster and more efficient.",
        keywords: ["digital","google forms","technology","online","data collection","exit ticket"],
        whenToUse: "When you want to quickly gather and analyse exit ticket data, particularly if students have devices available.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Assessment: digital data-gathering tool",
        adjustmentCodes: ["M9","M17","P9"],
        hpAdjustments: ["HP-LE3"],
        taskTypes: ["create-assessment", "plan-unit"]
    },
    {
        id: "content-9",
        title: "Analogy Generator for Concept Accessibility",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Use AI to generate multiple analogies for abstract concepts, each from a different domain, allowing interest-based differentiation and making complex ideas concrete and accessible.",
        keywords: ["analogy","analogies","abstract","concrete","comparison","metaphor","explain","accessible","interest","concept","visualise","understand","simplify","connect"],
        whenToUse: "When content involves abstract concepts that students struggle to visualise. Particularly effective when introducing new topics or when students have diverse interests you can leverage.",
        continuumType: "flexible",
        continuumPosition: ["foundations","core","extension"],
        continuumPrimary: "extension",
        continuumNote: "Generates analogies to make abstract concepts concrete — serves as foundations support but extends when analogies build deeper conceptual connections across domains",
        adjustmentCodes: ["C6","M4"],
        hpAdjustments: ["HP-CH3"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-support"]
    },
    {
        id: "process-9",
        title: "Predictive Misconception Mapping",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Use AI to predict which parts of each tiered task will cause the most confusion and pre-write targeted reteaching scripts before the lesson, shifting misconception response from reactive to proactive.",
        keywords: ["misconception","predict","reteach","confusion","anticipate","error","mistake","stuck","struggling","intervention","clarity","responsive","proactive","tiered"],
        whenToUse: "After creating tiered activities or scaffolded tasks — before teaching. Especially valuable when teaching conceptually tricky content or when you want to prepare for likely confusion points.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Teacher planning: anticipates where students will struggle — informs what foundations support to prepare",
        adjustmentCodes: ["C2","M9"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "plan-sequence"]
    },
    {
        id: "scaffolding-8",
        title: "EALD Translation Bridge",
        category: "Scaffolding",
        step: "Step 6: Scaffolding",
        link: "step6-scaffolding.html",
        description: "Use AI to translate key instructions, vocabulary, or concept summaries into a student's home language, creating a bilingual bridge that supports comprehension while students develop English proficiency.",
        keywords: ["EALD","EAL","translation","bilingual","home language","translanguaging","L1","first language","multilingual","ESL","newly arrived","vocabulary","glossary","language support","cultural","bridge"],
        whenToUse: "When EALD students are struggling to access content because of language demands rather than conceptual difficulty. Particularly effective for newly arrived students or when introducing vocabulary-heavy content.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Creates bilingual bridges so students can access content through their home language",
        adjustmentCodes: ["C1","C6","M10","M16"],
        hpAdjustments: [],
        taskTypes: ["diff-lesson", "setup-systems"]
    },
    {
        id: "assessment-11",
        title: "Bias & Cultural Assumption Audit",
        category: "Assessment & Response",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "Prompt the AI to critically examine any differentiated resource for unspoken cultural assumptions, socioeconomic bias, or representation gaps before it reaches students.",
        keywords: ["bias","cultural","assumption","audit","inclusion","diversity","equity","representation","respectful tasks","socioeconomic","EALD","family","review","quality check"],
        whenToUse: "After generating any differentiated resource. Particularly important when creating materials for diverse classrooms or when tasks reference home environments, family structures, or out-of-school activities.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Quality assurance: reviews differentiated materials for bias",
        adjustmentCodes: [],
        hpAdjustments: [],
        taskTypes: ["create-assessment", "plan-sequence"]
    },
    {
        id: "assessment-12",
        title: "The Devil's Advocate — AI Self-Critique",
        category: "Assessment & Response",
        step: "Step 7: Implementation & Assessment",
        link: "step7-implement.html",
        description: "After generating differentiated materials, prompt the AI to critically evaluate its own output from a student's perspective — identifying what's boring, confusing, or built on faulty assumptions.",
        keywords: ["critique","review","evaluate","quality","check","disengaged","boring","assumptions","self-critique","devil's advocate","engagement","respectful tasks","audit","revise"],
        whenToUse: "After creating any differentiated resource. Use as a quality check before finalising materials, especially when you've been working on something for a while and need fresh eyes.",
        continuumType: "excluded",
        continuumPosition: [],
        continuumPrimary: null,
        continuumNote: "Quality assurance: critiques AI-generated materials",
        adjustmentCodes: [],
        hpAdjustments: [],
        taskTypes: ["create-assessment", "plan-sequence"]
    },
    {
        id: "content-10",
        title: "Cross-Curricular Connections",
        category: "Content",
        step: "Step 3: Content",
        link: "step3-content.html",
        description: "Students explore how the core concept connects to other subject areas, identifying patterns, parallels, and principles that transfer across disciplines.",
        keywords: ["cross-curricular","transfer","connections","interdisciplinary","patterns","principles","deep learning","subjects","application","extension"],
        whenToUse: "When students have solid understanding of the core concept and you want to deepen it by helping them see its broader significance.",
        continuumType: "fixed",
        continuumPosition: ["extension"],
        continuumPrimary: "extension",
        continuumNote: "Extends understanding by connecting the core concept to other subject areas — building transfer that signals deep, flexible knowledge",
        adjustmentCodes: [],
        hpAdjustments: ["HP-CH3"],
        taskTypes: ["adjust-resource", "diff-lesson", "ideate-extension"]
    },
    {
        id: "process-10",
        title: "Independent Investigation Projects",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Students who have demonstrated mastery design and pursue their own investigation into a related question — choosing a focus, planning their approach, gathering evidence, and presenting findings.",
        keywords: ["investigation","inquiry","independent","research","project","self-directed","extension","mastery","deep learning","open-ended"],
        whenToUse: "When formative data shows students have genuinely mastered the core concept and need meaningful extension.",
        continuumType: "fixed",
        continuumPosition: ["extension"],
        continuumPrimary: "extension",
        continuumNote: "Students who've grasped the core learning intention pursue self-directed inquiry — applying understanding in new contexts",
        adjustmentCodes: ["C11","P6"],
        hpAdjustments: ["HP-CX2","HP-CH3","HP-CO1"],
        taskTypes: ["diff-lesson", "ideate-support"]
    },
    {
        id: "process-11",
        title: "Perspective Shifting & Complexity Tasks",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Students examine the core concept from multiple, potentially conflicting perspectives — considering different stakeholders, cultural viewpoints, time periods, or disciplinary lenses.",
        keywords: ["perspectives","multiple viewpoints","complexity","ambiguity","stakeholders","critical thinking","analysis","extension","depth"],
        whenToUse: "When the core concept has genuine complexity that simpler treatment has flattened.",
        continuumType: "fixed",
        continuumPosition: ["extension"],
        continuumPrimary: "extension",
        continuumNote: "Challenges students to examine the core concept from multiple perspectives — building capacity for complexity and ambiguity",
        adjustmentCodes: [],
        hpAdjustments: ["HP-CX1","HP-CX2"],
        taskTypes: ["plan-sequence", "plan-unit"]
    },
    {
        id: "process-12",
        title: "Mentoring & Teaching Others",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "Students consolidate and deepen their understanding by teaching the core concept to an authentic audience — peers, younger students, or parents.",
        keywords: ["teaching","mentoring","peer teaching","explain","consolidate","deepen","cross-age","presentation","mastery","extension"],
        whenToUse: "When students have demonstrated genuine mastery and would benefit from restructuring their knowledge for someone else.",
        continuumType: "fixed",
        continuumPosition: ["extension"],
        continuumPrimary: "extension",
        continuumNote: "Students who've mastered the core concept deepen understanding by teaching it to others",
        adjustmentCodes: ["C12","E3"],
        hpAdjustments: ["HP-CX2"],
        taskTypes: ["diff-lesson", "setup-systems"]
    },
    {
        id: "process-13",
        title: "Structured Academic Controversy",
        category: "Process",
        step: "Step 3: Process",
        link: "step3-process.html",
        description: "A structured discussion format where students examine a proposition related to the core learning intention — arguing one position, switching sides, then seeking consensus.",
        keywords: ["debate","discussion","structured","controversy","argumentation","evidence","perspectives","critical thinking","consensus"],
        whenToUse: "When the core concept involves a question or tension that can be examined from more than one position.",
        continuumType: "fixed",
        continuumPosition: ["core"],
        continuumPrimary: "core",
        continuumNote: "A structured discussion that deepens engagement with the core learning intention through evidence-based argumentation",
        adjustmentCodes: ["M11"],
        hpAdjustments: ["HP-CX1","HP-CX3","HP-CH2"],
        taskTypes: ["plan-sequence", "plan-unit", "setup-systems"]
    },
    {
        id: "product-9",
        title: "Scaffolded Demonstration Templates",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Pre-structured templates that help students organise and present their understanding when open-ended formats feel overwhelming. The scaffold supports organisation, not thinking.",
        keywords: ["template","scaffold","structure","organise","poster","presentation","report","framework","executive function","foundations"],
        whenToUse: "When students understand the concept but freeze when asked to show what they know in an open format.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Provides structured templates for demonstrating learning — reducing the organisational barrier so students can show what they know",
        adjustmentCodes: ["C10","P3","P10"],
        hpAdjustments: [],
        taskTypes: ["create-assessment", "ideate-extension"]
    },
    {
        id: "product-10",
        title: "Oral & Visual Demonstration Alternatives",
        category: "Product",
        step: "Step 3: Product",
        link: "step3-product.html",
        description: "Structured pathways for students to demonstrate understanding through speaking, drawing, building, or performing rather than writing.",
        keywords: ["oral","visual","alternative","non-written","recording","diagram","model","demonstration","EALD","dysgraphia","mode choice"],
        whenToUse: "When students understand the concept but struggle with written expression.",
        continuumType: "fixed",
        continuumPosition: ["foundations"],
        continuumPrimary: "foundations",
        continuumNote: "Offers non-written demonstration options with structured support — ensuring writing ability doesn't mask conceptual understanding",
        adjustmentCodes: ["P2","P4","P9"],
        hpAdjustments: ["HP-CO3"],
        taskTypes: ["create-assessment", "ideate-support", "ideate-extension"]
    }
];
